plugins {
    id 'java'
    id 'biz.aQute.bnd.builder' // To add OSGi support
}

group 'com.github.trosenkrantz'
version '1.0.8'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
        vendor = JvmVendorSpec.AZUL
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.2'
    testImplementation 'org.mockito:mockito-core:3.12.4'

    testRuntimeOnly(libs.junit.launcher) // Declaring test framework explicitly as recommended by Gradle: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
}

// Expose everything through OSGi
tasks.named('jar', Jar) {
    bundle {
        bnd('-exportcontents': 'com.github.trosenkrantz.sync.util.*')
    }
}

test {
    useJUnitPlatform()
}
