version: 2 # use CircleCI 2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}--{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: chmod +x gradlew
      - run: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}--{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - store_test_results:
          path: build/test-results/
      - store_artifacts:
          path: build/libs/
