version: 2 # use CircleCI 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}--{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Build
          command: |
            chmod +x gradlew
            ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}--{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - store_test_results:
          path: build/test-results/
      - store_artifacts:
          path: build/distributions/
