name: Build

on:
  push:
  schedule:
    - cron: '0 0 1 * *' # First day of every month
  workflow_dispatch: # Enables option to manually trigger build

permissions:
  contents: write # Gives permissions to push tags as well as create and update releases

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check Out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload Package
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: Package
          path: build/libs
          if-no-files-found: error

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: Test Results
          path: '**/build/reports/tests/test/**'
          if-no-files-found: error

      - name: Move Snapshot Tag
        run: |
          git tag -f snapshot
          git push -f origin snapshot

      - name: Delete Existing Snapshot Release
        run: |
          gh release delete snapshot --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Snapshot
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          tag_name: snapshot
          name: Snapshot
          prerelease: true
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
